var array = [
   {
      "clue":"Cripple",
      "length":4,
      "position":1,
      "answer":"    ",
      "startx":1,
      "starty":1,
      "orientation":"across",
      "answers":[
         {
            "name":"NUMB",
            "conf":5
         },
         {
            "name":"HALT",
            "conf":5
         },
         {
            "name":"HARM",
            "conf":5
         },
         {
            "name":"DAZE",
            "conf":5
         },
         {
            "name":"GIMP",
            "conf":5
         },
         {
            "name":"DING",
            "conf":5
         },
         {
            "name":"RUIN",
            "conf":5
         },
         {
            "name":"STUN",
            "conf":5
         },
         {
            "name":"WARP",
            "conf":5
         },
         {
            "name":"HURT",
            "conf":5
         },
         {
            "name":"CURB",
            "conf":5
         },
         {
            "name":"LAME",
            "conf":5
         },
         {
            "name":"DULL",
            "conf":5
         },
         {
            "name":"HACK",
            "conf":5
         },
         {
            "name":"MAUL",
            "conf":5
         },
         {
            "name":"CLOG",
            "conf":5
         },
         {
            "name":"MAIM",
            "conf":5
         },
         {
            "name":"HOCK",
            "conf":5
         },
         {
            "name":"UPON",
            "conf":1
         },
         {
            "name":"HELP",
            "conf":1
         }
      ]
   },
   {
      "clue":"Chorus member",
      "length":4,
      "position":5,
      "answer":"    ",
      "startx":6,
      "starty":1,
      "orientation":"across",
      "answers":[
         {
            "name":"BASS",
            "conf":5
         },
         {
            "name":"ALTO",
            "conf":5
         },
         {
            "name":"SING",
            "conf":1
         },
         {
            "name":"HYMN",
            "conf":1
         },
         {
            "name":"TUNE",
            "conf":1
         },
         {
            "name":"SONG",
            "conf":1
         },
         {
            "name":"LILT",
            "conf":1
         },
         {
            "name":"ELSE",
            "conf":1
         },
         {
            "name":"ZACH",
            "conf":1
         },
         {
            "name":"PAPP",
            "conf":1
         },
         {
            "name":"GERE",
            "conf":1
         },
         {
            "name":"ELSA",
            "conf":1
         },
         {
            "name":"AMEN",
            "conf":1
         },
         {
            "name":"TIME",
            "conf":1
         },
         {
            "name":"IDID",
            "conf":1
         },
         {
            "name":"ICAN",
            "conf":1
         },
         {
            "name":"LINE",
            "conf":1
         },
         {
            "name":"YEAH",
            "conf":1
         },
         {
            "name":"BOOS",
            "conf":1
         },
         {
            "name":"PAIN",
            "conf":1
         },
         {
            "name":"DAYO",
            "conf":1
         },
         {
            "name":"YAYS",
            "conf":1
         },
         {
            "name":"RAHS",
            "conf":1
         }
      ]
   },
   {
      "clue":"Old adders",
      "length":5,
      "position":9,
      "answer":"     ",
      "startx":11,
      "starty":1,
      "orientation":"across",
      "answers":[
         {
            "name":"ABACI",
            "conf":5
         },
         {
            "name":"VENOM",
            "conf":1
         },
         {
            "name":"FANGS",
            "conf":1
         }
      ]
   },
   {
      "clue":"Alan of \"The Seduction of Joe Tynan\"",
      "length":4,
      "position":14,
      "answer":"    ",
      "startx":1,
      "starty":2,
      "orientation":"across",
      "answers":[
         {
            "name":"ALDA",
            "conf":5
         },
         {
            "name":"LADD",
            "conf":3
         },
         {
            "name":"CAPP",
            "conf":2
         },
         {
            "name":"JAVA",
            "conf":2
         }
      ]
   },
   {
      "clue":"Ballet move",
      "length":4,
      "position":15,
      "answer":"    ",
      "startx":6,
      "starty":2,
      "orientation":"across",
      "answers":[
         {
            "name":"LEAP",
            "conf":5
         },
         {
            "name":"PLIE",
            "conf":5
         },
         {
            "name":"JETE",
            "conf":5
         },
         {
            "name":"ALLE",
            "conf":2
         },
         {
            "name":"AXEL",
            "conf":1
         },
         {
            "name":"NITE",
            "conf":1
         },
         {
            "name":"AMOR",
            "conf":1
         },
         {
            "name":"FAUN",
            "conf":1
         },
         {
            "name":"ERTE",
            "conf":1
         },
         {
            "name":"SWAN",
            "conf":1
         },
         {
            "name":"GALA",
            "conf":1
         },
         {
            "name":"TRUE",
            "conf":1
         },
         {
            "name":"AGON",
            "conf":1
         },
         {
            "name":"ANNA",
            "conf":1
         },
         {
            "name":"TUTU",
            "conf":1
         },
         {
            "name":"CODA",
            "conf":1
         },
         {
            "name":"IGOR",
            "conf":1
         }
      ]
   },
   {
      "clue":"Early computer language",
      "length":5,
      "position":16,
      "answer":"     ",
      "startx":11,
      "starty":2,
      "orientation":"across",
      "answers":[
         {
            "name":"BASIC",
            "conf":5
         },
         {
            "name":"ALGOL",
            "conf":5
         },
         {
            "name":"COBOL",
            "conf":5
         },
         {
            "name":"ENIAC",
            "conf":2
         },
         {
            "name":"ATARI",
            "conf":2
         },
         {
            "name":"OCTAL",
            "conf":2
         },
         {
            "name":"AOLER",
            "conf":2
         },
         {
            "name":"TURBO",
            "conf":2
         }
      ]
   },
   {
      "clue":"Light gas",
      "length":4,
      "position":17,
      "answer":"    ",
      "startx":1,
      "starty":3,
      "orientation":"across",
      "answers":[
         {
            "name":"NEON",
            "conf":5
         },
         {
            "name":"IONE",
            "conf":1
         },
         {
            "name":"ESSO",
            "conf":1
         },
         {
            "name":"HAHA",
            "conf":1
         },
         {
            "name":"RAGE",
            "conf":1
         },
         {
            "name":"SHEL",
            "conf":1
         },
         {
            "name":"MANN",
            "conf":1
         },
         {
            "name":"SOFT",
            "conf":1
         },
         {
            "name":"AMOS",
            "conf":1
         },
         {
            "name":"EASY",
            "conf":1
         },
         {
            "name":"PYRE",
            "conf":1
         },
         {
            "name":"NOVA",
            "conf":1
         },
         {
            "name":"ALES",
            "conf":1
         },
         {
            "name":"TRUE",
            "conf":1
         },
         {
            "name":"ISEE",
            "conf":1
         },
         {
            "name":"SEEA",
            "conf":1
         },
         {
            "name":"GOTA",
            "conf":1
         }
      ]
   },
   {
      "clue":"Gawk at",
      "length":4,
      "position":18,
      "answer":"    ",
      "startx":6,
      "starty":3,
      "orientation":"across",
      "answers":[
         {
            "name":"OGLE",
            "conf":5
         },
         {
            "name":"LEER",
            "conf":2
         },
         {
            "name":"PEER",
            "conf":1
         },
         {
            "name":"LAMP",
            "conf":1
         },
         {
            "name":"LOOK",
            "conf":1
         },
         {
            "name":"BEAM",
            "conf":1
         },
         {
            "name":"PIPE",
            "conf":1
         },
         {
            "name":"BORE",
            "conf":1
         },
         {
            "name":"GAPE",
            "conf":1
         },
         {
            "name":"GAZE",
            "conf":1
         },
         {
            "name":"SCAN",
            "conf":1
         },
         {
            "name":"YAWP",
            "conf":1
         },
         {
            "name":"GAWP",
            "conf":1
         }
      ]
   },
   {
      "clue":"Type of type",
      "length":5,
      "position":19,
      "answer":"     ",
      "startx":11,
      "starty":3,
      "orientation":"across",
      "answers":[
         {
            "name":"ELITE",
            "conf":5
         },
         {
            "name":"ROMAN",
            "conf":5
         },
         {
            "name":"AGATE",
            "conf":5
         },
         {
            "name":"IONIC",
            "conf":2
         },
         {
            "name":"SERIF",
            "conf":2
         },
         {
            "name":"FONTS",
            "conf":2
         },
         {
            "name":"ITALS",
            "conf":2
         }
      ]
   },
   {
      "clue":"Examination, redundantly",
      "length":13,
      "position":20,
      "answer":"             ",
      "startx":2,
      "starty":4,
      "orientation":"across",
      "answers":[
         {
            "name":"CLOSESCRUTINY",
            "conf":5
         },
         {
            "name":"CONNIPTIONFIT",
            "conf":1
         },
         {
            "name":"NEWINNOVATION",
            "conf":1
         },
         {
            "name":"BLENDTOGETHER",
            "conf":1
         },
         {
            "name":"INTERROGATION",
            "conf":1
         },
         {
            "name":"CONTEMPLATION",
            "conf":1
         },
         {
            "name":"CONSIDERATION",
            "conf":1
         },
         {
            "name":"CORROBORATION",
            "conf":1
         },
         {
            "name":"SECONDTHOUGHT",
            "conf":1
         },
         {
            "name":"INVESTIGATION",
            "conf":1
         },
         {
            "name":"TRIALANDERROR",
            "conf":1
         },
         {
            "name":"INTROSPECTION",
            "conf":1
         },
         {
            "name":"POSTOPERATIVE",
            "conf":1
         },
         {
            "name":"QUESTIONNAIRE",
            "conf":1
         },
         {
            "name":"PERLUSTRATION",
            "conf":1
         },
         {
            "name":"YEARLYCHECKUP",
            "conf":1
         }
      ]
   },
   {
      "clue":"Increase, with \"up\"",
      "length":3,
      "position":23,
      "answer":"   ",
      "startx":4,
      "starty":5,
      "orientation":"across",
      "answers":[
         {
            "name":"AMP",
            "conf":5
         },
         {
            "name":"REV",
            "conf":5
         },
         {
            "name":"EKE",
            "conf":2
         },
         {
            "name":"ADD",
            "conf":2
         },
         {
            "name":"GET",
            "conf":1
         },
         {
            "name":"LEG",
            "conf":1
         },
         {
            "name":"TAG",
            "conf":1
         },
         {
            "name":"FAN",
            "conf":1
         },
         {
            "name":"PAD",
            "conf":1
         },
         {
            "name":"WAX",
            "conf":1
         },
         {
            "name":"CPI",
            "conf":1
         },
         {
            "name":"INT",
            "conf":1
         },
         {
            "name":"IRE",
            "conf":1
         },
         {
            "name":"SEX",
            "conf":1
         }
      ]
   },
   {
      "clue":"Quick on the uptake",
      "length":3,
      "position":24,
      "answer":"   ",
      "startx":9,
      "starty":5,
      "orientation":"across",
      "answers":[
         {
            "name":"APT",
            "conf":5
         },
         {
            "name":"DIM",
            "conf":4
         }
      ]
   },
   {
      "clue":"Frisk, with \"down\"",
      "length":3,
      "position":25,
      "answer":"   ",
      "startx":1,
      "starty":6,
      "orientation":"across",
      "answers":[
         {
            "name":"PAT",
            "conf":5
         },
         {
            "name":"HOE",
            "conf":2
         },
         {
            "name":"MOW",
            "conf":2
         },
         {
            "name":"BOG",
            "conf":2
         },
         {
            "name":"PUT",
            "conf":2
         },
         {
            "name":"LET",
            "conf":2
         },
         {
            "name":"FUN",
            "conf":1
         },
         {
            "name":"HOP",
            "conf":1
         },
         {
            "name":"FAN",
            "conf":1
         },
         {
            "name":"TSA",
            "conf":1
         }
      ]
   },
   {
      "clue":"\"The Way We __\"",
      "length":4,
      "position":28,
      "answer":"    ",
      "startx":5,
      "starty":6,
      "orientation":"across",
      "answers":[
         {
            "name":"WERE",
            "conf":5
         },
         {
            "name":"EARN",
            "conf":3
         },
         {
            "name":"ALAN",
            "conf":3
         },
         {
            "name":"OBEY",
            "conf":2
         },
         {
            "name":"ONOR",
            "conf":2
         },
         {
            "name":"HADA",
            "conf":2
         },
         {
            "name":"HATE",
            "conf":2
         }
      ]
   },
   {
      "clue":"Perfectos, e.g.",
      "length":6,
      "position":31,
      "answer":"      ",
      "startx":10,
      "starty":6,
      "orientation":"across",
      "answers":[
         {
            "name":"CIGARS",
            "conf":5
         },
         {
            "name":"COMEDY",
            "conf":2
         },
         {
            "name":"SHRIEK",
            "conf":2
         },
         {
            "name":"LAMENT",
            "conf":2
         },
         {
            "name":"BIOPIC",
            "conf":2
         },
         {
            "name":"MEMOIR",
            "conf":2
         },
         {
            "name":"SATIRE",
            "conf":2
         },
         {
            "name":"SIMILE",
            "conf":2
         }
      ]
   },
   {
      "clue":"Director Kazan",
      "length":4,
      "position":36,
      "answer":"    ",
      "startx":1,
      "starty":7,
      "orientation":"across",
      "answers":[
         {
            "name":"ELIA",
            "conf":5
         }
      ]
   },
   {
      "clue":"Colonel or captain",
      "length":4,
      "position":38,
      "answer":"    ",
      "startx":6,
      "starty":7,
      "orientation":"across",
      "answers":[
         {
            "name":"RANK",
            "conf":5
         },
         {
            "name":"BELL",
            "conf":2
         },
         {
            "name":"SCOT",
            "conf":2
         },
         {
            "name":"AMIS",
            "conf":1
         },
         {
            "name":"ANTZ",
            "conf":1
         },
         {
            "name":"NAZI",
            "conf":1
         },
         {
            "name":"CLUE",
            "conf":1
         },
         {
            "name":"ROPE",
            "conf":1
         },
         {
            "name":"RAYE",
            "conf":1
         }
      ]
   },
   {
      "clue":"Gymnast Comaneci",
      "length":5,
      "position":40,
      "answer":"     ",
      "startx":11,
      "starty":7,
      "orientation":"across",
      "answers":[
         {
            "name":"NADIA",
            "conf":5
         },
         {
            "name":"AGILE",
            "conf":1
         },
         {
            "name":"LITHE",
            "conf":1
         },
         {
            "name":"KERRI",
            "conf":1
         },
         {
            "name":"ELISE",
            "conf":1
         },
         {
            "name":"RIGBY",
            "conf":1
         },
         {
            "name":"MITCH",
            "conf":1
         },
         {
            "name":"STRUG",
            "conf":1
         },
         {
            "name":"NELLI",
            "conf":1
         },
         {
            "name":"OLGAS",
            "conf":1
         },
         {
            "name":"CATHY",
            "conf":1
         },
         {
            "name":"IRONX",
            "conf":1
         }
      ]
   },
   {
      "clue":"Pestering, redundantly",
      "length":15,
      "position":41,
      "answer":"               ",
      "startx":1,
      "starty":8,
      "orientation":"across",
      "answers":[
         {
            "name":"CONSTANTNAGGING",
            "conf":5
         },
         {
            "name":"DOCTORATEDEGREE",
            "conf":1
         },
         {
            "name":"SQUAREDSTRAIGHT",
            "conf":1
         },
         {
            "name":"FELLOWCOLLEAGUE",
            "conf":1
         },
         {
            "name":"ORIGINALFOUNDER",
            "conf":1
         },
         {
            "name":"UNSOLVEDMYSTERY",
            "conf":1
         },
         {
            "name":"MAINPROTAGONIST",
            "conf":1
         },
         {
            "name":"VISIBLETOTHEEYE",
            "conf":1
         },
         {
            "name":"ADVANCEPLANNING",
            "conf":1
         }
      ]
   },
   {
      "clue":"Uniform shade",
      "length":5,
      "position":44,
      "answer":"     ",
      "startx":1,
      "starty":9,
      "orientation":"across",
      "answers":[
         {
            "name":"OLIVE",
            "conf":5
         },
         {
            "name":"KHAKI",
            "conf":5
         },
         {
            "name":"DITTO",
            "conf":1
         },
         {
            "name":"DRESS",
            "conf":1
         },
         {
            "name":"HABIT",
            "conf":1
         },
         {
            "name":"LEVEL",
            "conf":1
         },
         {
            "name":"ALIKE",
            "conf":1
         },
         {
            "name":"PLANE",
            "conf":1
         },
         {
            "name":"CHINO",
            "conf":1
         },
         {
            "name":"SEWON",
            "conf":1
         },
         {
            "name":"DRABS",
            "conf":1
         },
         {
            "name":"THREE",
            "conf":1
         },
         {
            "name":"NAMES",
            "conf":1
         },
         {
            "name":"SILKS",
            "conf":1
         },
         {
            "name":"SOOTY",
            "conf":1
         },
         {
            "name":"GSUIT",
            "conf":1
         },
         {
            "name":"MIXED",
            "conf":1
         },
         {
            "name":"SKIRT",
            "conf":1
         },
         {
            "name":"TUNIC",
            "conf":1
         },
         {
            "name":"BERET",
            "conf":1
         },
         {
            "name":"BRAID",
            "conf":1
         },
         {
            "name":"CADET",
            "conf":1
         },
         {
            "name":"PLAIN",
            "conf":1
         }
      ]
   },
   {
      "clue":"Student driver, usuaHy",
      "length":4,
      "position":45,
      "answer":"    ",
      "startx":7,
      "starty":9,
      "orientation":"across",
      "answers":[
         {
            "name":"TEEN",
            "conf":2
         },
         {
            "name":"MADD",
            "conf":1
         },
         {
            "name":"HOKE",
            "conf":1
         },
         {
            "name":"AFAD",
            "conf":1
         },
         {
            "name":"ELLE",
            "conf":1
         },
         {
            "name":"INGE",
            "conf":1
         },
         {
            "name":"OTTO",
            "conf":1
         },
         {
            "name":"ERIC",
            "conf":1
         },
         {
            "name":"SOPH",
            "conf":1
         },
         {
            "name":"WONK",
            "conf":1
         },
         {
            "name":"STAR",
            "conf":1
         },
         {
            "name":"CRAM",
            "conf":1
         }
      ]
   },
   {
      "clue":"Wrigley Field slugger",
      "length":4,
      "position":46,
      "answer":"    ",
      "startx":12,
      "starty":9,
      "orientation":"across",
      "answers":[
         {
            "name":"SOSA",
            "conf":5
         },
         {
            "name":"TARP",
            "conf":2
         },
         {
            "name":"ALOU",
            "conf":2
         },
         {
            "name":"CUBS",
            "conf":2
         },
         {
            "name":"RAMP",
            "conf":1
         },
         {
            "name":"BATS",
            "conf":1
         },
         {
            "name":"TIER",
            "conf":1
         },
         {
            "name":"BOOG",
            "conf":1
         },
         {
            "name":"MIZE",
            "conf":1
         },
         {
            "name":"TINO",
            "conf":1
         },
         {
            "name":"AROD",
            "conf":1
         },
         {
            "name":"STAN",
            "conf":1
         },
         {
            "name":"ENOS",
            "conf":1
         }
      ]
   },
   {
      "clue":"Gets smart with",
      "length":6,
      "position":47,
      "answer":"      ",
      "startx":1,
      "starty":10,
      "orientation":"across",
      "answers":[
         {
            "name":"SASSES",
            "conf":5
         },
         {
            "name":"LEARNS",
            "conf":2
         },
         {
            "name":"SASSED",
            "conf":2
         },
         {
            "name":"FELDON",
            "conf":1
         },
         {
            "name":"DEANNA",
            "conf":1
         },
         {
            "name":"WISEUP",
            "conf":1
         },
         {
            "name":"NEATEN",
            "conf":1
         },
         {
            "name":"PERTLY",
            "conf":1
         },
         {
            "name":"ASTUTE",
            "conf":1
         },
         {
            "name":"GIFTED",
            "conf":1
         },
         {
            "name":"SPIFFY",
            "conf":1
         },
         {
            "name":"PREENS",
            "conf":1
         },
         {
            "name":"SLOWER",
            "conf":1
         }
      ]
   },
   {
      "clue":"Try for a part",
      "length":4,
      "position":49,
      "answer":"    ",
      "startx":8,
      "starty":10,
      "orientation":"across",
      "answers":[
         {
            "name":"READ",
            "conf":5
         },
         {
            "name":"BOWL",
            "conf":3
         },
         {
            "name":"LEAN",
            "conf":3
         },
         {
            "name":"SWAT",
            "conf":3
         },
         {
            "name":"KICK",
            "conf":3
         },
         {
            "name":"TOIL",
            "conf":2
         },
         {
            "name":"WORK",
            "conf":2
         },
         {
            "name":"SEEK",
            "conf":2
         },
         {
            "name":"PUSH",
            "conf":2
         },
         {
            "name":"MOIL",
            "conf":2
         },
         {
            "name":"POSE",
            "conf":2
         },
         {
            "name":"FAKE",
            "conf":2
         },
         {
            "name":"INON",
            "conf":2
         },
         {
            "name":"ASSN",
            "conf":2
         },
         {
            "name":"ARTS",
            "conf":2
         },
         {
            "name":"ACTS",
            "conf":2
         },
         {
            "name":"LENT",
            "conf":2
         },
         {
            "name":"ACCT",
            "conf":2
         }
      ]
   },
   {
      "clue":"One of 100 in D.C.",
      "length":3,
      "position":51,
      "answer":"   ",
      "startx":13,
      "starty":10,
      "orientation":"across",
      "answers":[
         {
            "name":"SEN",
            "conf":5
         },
         {
            "name":"ANO",
            "conf":4
         },
         {
            "name":"STS",
            "conf":3
         },
         {
            "name":"MRT",
            "conf":3
         },
         {
            "name":"IRS",
            "conf":3
         },
         {
            "name":"OAS",
            "conf":3
         },
         {
            "name":"STO",
            "conf":2
         },
         {
            "name":"ORE",
            "conf":2
         },
         {
            "name":"TEN",
            "conf":2
         }
      ]
   },
   {
      "clue":"Conquistador's prize",
      "length":3,
      "position":52,
      "answer":"   ",
      "startx":5,
      "starty":11,
      "orientation":"across",
      "answers":[
         {
            "name":"ORO",
            "conf":5
         },
         {
            "name":"INA",
            "conf":1
         }
      ]
   },
   {
      "clue":"Whisper sweet nothings",
      "length":3,
      "position":54,
      "answer":"   ",
      "startx":10,
      "starty":11,
      "orientation":"across",
      "answers":[
         {
            "name":"COO",
            "conf":5
         },
         {
            "name":"WOO",
            "conf":3
         },
         {
            "name":"ALL",
            "conf":1
         },
         {
            "name":"TIP",
            "conf":1
         },
         {
            "name":"FRY",
            "conf":1
         },
         {
            "name":"TAP",
            "conf":1
         },
         {
            "name":"HUM",
            "conf":1
         },
         {
            "name":"EAR",
            "conf":1
         },
         {
            "name":"CRY",
            "conf":1
         },
         {
            "name":"IDO",
            "conf":1
         },
         {
            "name":"CUE",
            "conf":1
         }
      ]
   },
   {
      "clue":"Angry outburst, redundantly",
      "length":13,
      "position":56,
      "answer":"             ",
      "startx":2,
      "starty":12,
      "orientation":"across",
      "answers":[
         {
            "name":"CONNIPTIONFIT",
            "conf":5
         },
         {
            "name":"CLOSESCRUTINY",
            "conf":1
         },
         {
            "name":"NEWINNOVATION",
            "conf":1
         },
         {
            "name":"BLENDTOGETHER",
            "conf":1
         },
         {
            "name":"DEMONSTRATION",
            "conf":1
         },
         {
            "name":"TONGUELASHING",
            "conf":1
         },
         {
            "name":"UNPREDICTABLE",
            "conf":1
         },
         {
            "name":"UNCOMFORTABLE",
            "conf":1
         },
         {
            "name":"TEMPERAMENTAL",
            "conf":1
         },
         {
            "name":"BESIDEONESELF",
            "conf":1
         },
         {
            "name":"HEATABSORBING",
            "conf":1
         },
         {
            "name":"QUICKTEMPERED",
            "conf":1
         },
         {
            "name":"SCINTILLATING",
            "conf":1
         },
         {
            "name":"HITTHECEILING",
            "conf":1
         },
         {
            "name":"GETINTOATIZZY",
            "conf":1
         },
         {
            "name":"BITTERHERBERT",
            "conf":1
         },
         {
            "name":"GRIPESOFWRATH",
            "conf":1
         },
         {
            "name":"TAKEEXCEPTION",
            "conf":1
         },
         {
            "name":"BLOWONESSTACK",
            "conf":1
         },
         {
            "name":"MAUVEWITHRAGE",
            "conf":1
         }
      ]
   },
   {
      "clue":"Oscar winner Foster",
      "length":5,
      "position":63,
      "answer":"     ",
      "startx":1,
      "starty":13,
      "orientation":"across",
      "answers":[
         {
            "name":"JODIE",
            "conf":5
         },
         {
            "name":"HOUSE",
            "conf":1
         },
         {
            "name":"NURSE",
            "conf":1
         },
         {
            "name":"SERVE",
            "conf":1
         },
         {
            "name":"TREAT",
            "conf":1
         },
         {
            "name":"IROAM",
            "conf":1
         },
         {
            "name":"AGAIN",
            "conf":1
         },
         {
            "name":"GRIER",
            "conf":1
         },
         {
            "name":"PANIC",
            "conf":1
         },
         {
            "name":"NELLY",
            "conf":1
         },
         {
            "name":"KANES",
            "conf":1
         }
      ]
   },
   {
      "clue":"Unable to decide",
      "length":4,
      "position":64,
      "answer":"    ",
      "startx":7,
      "starty":13,
      "orientation":"across",
      "answers":[
         {
            "name":"HUNG",
            "conf":5
         },
         {
            "name":"TORN",
            "conf":5
         },
         {
            "name":"FLIP",
            "conf":2
         },
         {
            "name":"LOTS",
            "conf":2
         },
         {
            "name":"LAGS",
            "conf":2
         },
         {
            "name":"COIN",
            "conf":2
         },
         {
            "name":"HAWS",
            "conf":2
         },
         {
            "name":"LOSE",
            "conf":2
         },
         {
            "name":"NEED",
            "conf":2
         },
         {
            "name":"ARES",
            "conf":2
         },
         {
            "name":"CANT",
            "conf":2
         },
         {
            "name":"VOID",
            "conf":2
         },
         {
            "name":"DULL",
            "conf":2
         },
         {
            "name":"LOST",
            "conf":2
         },
         {
            "name":"ASEA",
            "conf":2
         },
         {
            "name":"DEAF",
            "conf":2
         },
         {
            "name":"ARUT",
            "conf":2
         },
         {
            "name":"ABLE",
            "conf":1
         },
         {
            "name":"WEAK",
            "conf":1
         }
      ]
   },
   {
      "clue":"Took off",
      "length":4,
      "position":65,
      "answer":"    ",
      "startx":12,
      "starty":13,
      "orientation":"across",
      "answers":[
         {
            "name":"SHED",
            "conf":5
         },
         {
            "name":"ROSE",
            "conf":5
         },
         {
            "name":"LEFT",
            "conf":5
         },
         {
            "name":"WENT",
            "conf":5
         },
         {
            "name":"SPED",
            "conf":5
         },
         {
            "name":"BLEW",
            "conf":5
         },
         {
            "name":"FLEW",
            "conf":5
         },
         {
            "name":"FLED",
            "conf":5
         },
         {
            "name":"HIED",
            "conf":5
         },
         {
            "name":"TORE",
            "conf":2
         },
         {
            "name":"APED",
            "conf":2
         },
         {
            "name":"USED",
            "conf":2
         }
      ]
   },
   {
      "clue":"Maine college town",
      "length":5,
      "position":67,
      "answer":"     ",
      "startx":1,
      "starty":14,
      "orientation":"across",
      "answers":[
         {
            "name":"ORONO",
            "conf":5
         },
         {
            "name":"BATES",
            "conf":2
         },
         {
            "name":"COLBY",
            "conf":2
         },
         {
            "name":"TEMPE",
            "conf":2
         },
         {
            "name":"AZUSA",
            "conf":2
         },
         {
            "name":"BEREA",
            "conf":2
         },
         {
            "name":"HAVRE",
            "conf":2
         },
         {
            "name":"KEENE",
            "conf":2
         },
         {
            "name":"RIPON",
            "conf":2
         },
         {
            "name":"CASCO",
            "conf":1
         },
         {
            "name":"COHEN",
            "conf":1
         },
         {
            "name":"HOMER",
            "conf":1
         },
         {
            "name":"PINEY",
            "conf":1
         },
         {
            "name":"SNOWE",
            "conf":1
         },
         {
            "name":"STATI",
            "conf":1
         }
      ]
   },
   {
      "clue":"\"Zounds!\"",
      "length":4,
      "position":68,
      "answer":"    ",
      "startx":7,
      "starty":14,
      "orientation":"across",
      "answers":[
         {
            "name":"EGAD",
            "conf":5
         },
         {
            "name":"GOSH",
            "conf":5
         },
         {
            "name":"OATH",
            "conf":1
         }
      ]
   },
   {
      "clue":"Jacob's twin",
      "length":4,
      "position":69,
      "answer":"    ",
      "startx":12,
      "starty":14,
      "orientation":"across",
      "answers":[
         {
            "name":"ESAU",
            "conf":5
         },
         {
            "name":"MARC",
            "conf":1
         },
         {
            "name":"LEAH",
            "conf":1
         },
         {
            "name":"HERB",
            "conf":1
         },
         {
            "name":"LEVI",
            "conf":1
         },
         {
            "name":"IRIS",
            "conf":1
         },
         {
            "name":"ERIE",
            "conf":1
         },
         {
            "name":"OMAR",
            "conf":1
         },
         {
            "name":"ABEL",
            "conf":1
         },
         {
            "name":"ARON",
            "conf":1
         },
         {
            "name":"ERIC",
            "conf":1
         },
         {
            "name":"CHAN",
            "conf":1
         },
         {
            "name":"KYLE",
            "conf":1
         },
         {
            "name":"CHEN",
            "conf":1
         },
         {
            "name":"TAXI",
            "conf":1
         },
         {
            "name":"BERT",
            "conf":1
         },
         {
            "name":"LEIA",
            "conf":1
         },
         {
            "name":"LARA",
            "conf":1
         },
         {
            "name":"ARES",
            "conf":1
         },
         {
            "name":"ERIS",
            "conf":1
         },
         {
            "name":"NANS",
            "conf":1
         },
         {
            "name":"LORE",
            "conf":1
         },
         {
            "name":"ATRA",
            "conf":1
         },
         {
            "name":"TWIN",
            "conf":1
         },
         {
            "name":"SIZE",
            "conf":1
         }
      ]
   },
   {
      "clue":"Von Munchhausen, e.g.",
      "length":5,
      "position":70,
      "answer":"     ",
      "startx":1,
      "starty":15,
      "orientation":"across",
      "answers":[
         {
            "name":"LIARS",
            "conf":1
         },
         {
            "name":"YARNS",
            "conf":1
         },
         {
            "name":"BARON",
            "conf":1
         },
         {
            "name":"TRIER",
            "conf":1
         },
         {
            "name":"LEHAR",
            "conf":1
         },
         {
            "name":"ERICH",
            "conf":1
         },
         {
            "name":"WEBER",
            "conf":1
         },
         {
            "name":"SUPPE",
            "conf":1
         },
         {
            "name":"ESSEN",
            "conf":1
         },
         {
            "name":"SYDOW",
            "conf":1
         },
         {
            "name":"TRAPP",
            "conf":1
         }
      ]
   },
   {
      "clue":"Lady of Lisbon",
      "length":4,
      "position":71,
      "answer":"    ",
      "startx":7,
      "starty":15,
      "orientation":"across",
      "answers":[
         {
            "name":"DONA",
            "conf":5
         },
         {
            "name":"ELLA",
            "conf":2
         },
         {
            "name":"BESS",
            "conf":2
         },
         {
            "name":"HERA",
            "conf":2
         },
         {
            "name":"ETON",
            "conf":2
         },
         {
            "name":"ENID",
            "conf":2
         },
         {
            "name":"OONA",
            "conf":1
         },
         {
            "name":"ANOS",
            "conf":1
         },
         {
            "name":"RACO",
            "conf":1
         },
         {
            "name":"ROCA",
            "conf":1
         },
         {
            "name":"AMOR",
            "conf":1
         },
         {
            "name":"MAIO",
            "conf":1
         },
         {
            "name":"ESTE",
            "conf":1
         },
         {
            "name":"DOIS",
            "conf":1
         },
         {
            "name":"POCO",
            "conf":1
         }
      ]
   },
   {
      "clue":"Medium—_,",
      "length":4,
      "position":72,
      "answer":"    ",
      "startx":12,
      "starty":15,
      "orientation":"across",
      "answers":[
         {
            "name":"RARE",
            "conf":2
         },
         {
            "name":"AGAR",
            "conf":1
         },
         {
            "name":"ANTZ",
            "conf":1
         },
         {
            "name":"NEON",
            "conf":1
         },
         {
            "name":"AGER",
            "conf":1
         },
         {
            "name":"OILS",
            "conf":1
         },
         {
            "name":"HAIR",
            "conf":1
         },
         {
            "name":"SOAP",
            "conf":1
         },
         {
            "name":"JADE",
            "conf":1
         },
         {
            "name":"TILE",
            "conf":1
         },
         {
            "name":"ESTA",
            "conf":1
         },
         {
            "name":"IGET",
            "conf":1
         },
         {
            "name":"ROBO",
            "conf":1
         },
         {
            "name":"PEER",
            "conf":1
         },
         {
            "name":"ONCE",
            "conf":1
         },
         {
            "name":"DOAS",
            "conf":1
         },
         {
            "name":"EINE",
            "conf":1
         },
         {
            "name":"SHES",
            "conf":1
         },
         {
            "name":"ANDI",
            "conf":1
         },
         {
            "name":"CEST",
            "conf":1
         },
         {
            "name":"MEET",
            "conf":1
         },
         {
            "name":"WEVE",
            "conf":1
         },
         {
            "name":"ESTO",
            "conf":1
         },
         {
            "name":"IGOT",
            "conf":1
         }
      ]
   },
   {
      "clue":"\"Hoo—ey!\"",
      "length":3,
      "position":1,
      "answer":"   ",
      "startx":1,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"MAN",
            "conf":2
         },
         {
            "name":"SSW",
            "conf":1
         },
         {
            "name":"ENE",
            "conf":1
         },
         {
            "name":"OLE",
            "conf":1
         },
         {
            "name":"YAY",
            "conf":1
         },
         {
            "name":"CRY",
            "conf":1
         },
         {
            "name":"SOB",
            "conf":1
         },
         {
            "name":"YOO",
            "conf":1
         },
         {
            "name":"HEY",
            "conf":1
         },
         {
            "name":"RAH",
            "conf":1
         },
         {
            "name":"ADO",
            "conf":1
         }
      ]
   },
   {
      "clue":"Baldwin of \"Talk Radio\"",
      "length":4,
      "position":2,
      "answer":"    ",
      "startx":2,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"ALEC",
            "conf":5
         },
         {
            "name":"ERIC",
            "conf":3
         },
         {
            "name":"NEAL",
            "conf":3
         },
         {
            "name":"IMUS",
            "conf":3
         },
         {
            "name":"RUSH",
            "conf":3
         },
         {
            "name":"THOM",
            "conf":3
         },
         {
            "name":"WABC",
            "conf":2
         },
         {
            "name":"OPIE",
            "conf":2
         },
         {
            "name":"TINA",
            "conf":2
         },
         {
            "name":"RHEA",
            "conf":2
         },
         {
            "name":"PHIL",
            "conf":2
         },
         {
            "name":"MERV",
            "conf":2
         }
      ]
   },
   {
      "clue":"Elvis or Madonna, e.g.",
      "length":4,
      "position":3,
      "answer":"    ",
      "startx":3,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"IDOL",
            "conf":5
         },
         {
            "name":"ICON",
            "conf":3
         },
         {
            "name":"LADY",
            "conf":3
         },
         {
            "name":"ARON",
            "conf":2
         },
         {
            "name":"STAR",
            "conf":2
         },
         {
            "name":"ISLA",
            "conf":1
         },
         {
            "name":"RENI",
            "conf":1
         },
         {
            "name":"DARE",
            "conf":1
         },
         {
            "name":"ESTA",
            "conf":1
         },
         {
            "name":"SUCH",
            "conf":1
         },
         {
            "name":"YOUR",
            "conf":1
         },
         {
            "name":"GLAD",
            "conf":1
         },
         {
            "name":"ITUP",
            "conf":1
         },
         {
            "name":"NICE",
            "conf":1
         }
      ]
   },
   {
      "clue":"Lord's home",
      "length":5,
      "position":4,
      "answer":"     ",
      "startx":4,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"MANOR",
            "conf":5
         },
         {
            "name":"BARON",
            "conf":1
         },
         {
            "name":"NOBLE",
            "conf":1
         },
         {
            "name":"ANGEL",
            "conf":1
         },
         {
            "name":"THANE",
            "conf":1
         },
         {
            "name":"ISEEK",
            "conf":1
         },
         {
            "name":"TRACI",
            "conf":1
         },
         {
            "name":"SERFS",
            "conf":1
         },
         {
            "name":"FIVEO",
            "conf":1
         },
         {
            "name":"JESUS",
            "conf":1
         },
         {
            "name":"PATER",
            "conf":1
         },
         {
            "name":"DEBTS",
            "conf":1
         },
         {
            "name":"FIEFS",
            "conf":1
         }
      ]
   },
   {
      "clue":"Skin cream ingredient",
      "length":8,
      "position":5,
      "answer":"        ",
      "startx":6,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"ALOEVERA",
            "conf":5
         },
         {
            "name":"CLUBSODA",
            "conf":2
         },
         {
            "name":"AMERICAN",
            "conf":1
         },
         {
            "name":"ENDERMIC",
            "conf":1
         },
         {
            "name":"NAMWARTS",
            "conf":1
         },
         {
            "name":"IMPETIGO",
            "conf":1
         },
         {
            "name":"TATTOOED",
            "conf":1
         },
         {
            "name":"IRRITATE",
            "conf":1
         },
         {
            "name":"OPERATES",
            "conf":1
         },
         {
            "name":"SOLUTION",
            "conf":1
         },
         {
            "name":"TREASURE",
            "conf":1
         },
         {
            "name":"FAVORITE",
            "conf":1
         },
         {
            "name":"DEMOLISH",
            "conf":1
         },
         {
            "name":"EARNINGS",
            "conf":1
         },
         {
            "name":"DRESSING",
            "conf":1
         },
         {
            "name":"SKIMMILK",
            "conf":1
         },
         {
            "name":"EGGPLANT",
            "conf":1
         },
         {
            "name":"AMARETTO",
            "conf":1
         },
         {
            "name":"METHANOL",
            "conf":1
         },
         {
            "name":"MOLASSES",
            "conf":1
         },
         {
            "name":"IRISHALE",
            "conf":1
         },
         {
            "name":"NAVYBEAN",
            "conf":1
         }
      ]
   },
   {
      "clue":"Longevity at the box office",
      "length":4,
      "position":6,
      "answer":"    ",
      "startx":7,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"LEGS",
            "conf":5
         },
         {
            "name":"JAWS",
            "conf":4
         },
         {
            "name":"BOMB",
            "conf":4
         },
         {
            "name":"DIED",
            "conf":4
         },
         {
            "name":"LIES",
            "conf":3
         },
         {
            "name":"ADDS",
            "conf":3
         },
         {
            "name":"DOWN",
            "conf":2
         },
         {
            "name":"SENT",
            "conf":2
         },
         {
            "name":"REDD",
            "conf":2
         },
         {
            "name":"PAAR",
            "conf":2
         },
         {
            "name":"GATE",
            "conf":2
         },
         {
            "name":"STAR",
            "conf":2
         },
         {
            "name":"AWAY",
            "conf":2
         },
         {
            "name":"CELL",
            "conf":2
         },
         {
            "name":"LOGE",
            "conf":2
         },
         {
            "name":"LIFE",
            "conf":1
         }
      ]
   },
   {
      "clue":"Soft mineral",
      "length":4,
      "position":7,
      "answer":"    ",
      "startx":8,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"TALC",
            "conf":5
         },
         {
            "name":"TOQS",
            "conf":1
         },
         {
            "name":"MOHS",
            "conf":1
         },
         {
            "name":"NOUN",
            "conf":1
         },
         {
            "name":"ONYX",
            "conf":1
         },
         {
            "name":"OPAL",
            "conf":1
         },
         {
            "name":"CALX",
            "conf":1
         },
         {
            "name":"MICA",
            "conf":1
         },
         {
            "name":"IRON",
            "conf":1
         },
         {
            "name":"BATH",
            "conf":1
         },
         {
            "name":"JADE",
            "conf":1
         },
         {
            "name":"ZINC",
            "conf":1
         }
      ]
   },
   {
      "clue":"\"ll Trovatore,\" e.g.",
      "length":5,
      "position":8,
      "answer":"     ",
      "startx":9,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"OPERA",
            "conf":3
         },
         {
            "name":"VERDI",
            "conf":1
         },
         {
            "name":"IMBAD",
            "conf":1
         },
         {
            "name":"GOING",
            "conf":1
         },
         {
            "name":"LSATS",
            "conf":1
         },
         {
            "name":"ILLER",
            "conf":1
         }
      ]
   },
   {
      "clue":"Driving the getaway car for",
      "length":8,
      "position":9,
      "answer":"        ",
      "startx":11,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"ABETTING",
            "conf":5
         },
         {
            "name":"ESCAPING",
            "conf":1
         },
         {
            "name":"ESCHEWAL",
            "conf":1
         },
         {
            "name":"BREAKOUT",
            "conf":1
         },
         {
            "name":"SHUNNING",
            "conf":1
         },
         {
            "name":"OUTBREAK",
            "conf":1
         },
         {
            "name":"STTHOMAS",
            "conf":1
         },
         {
            "name":"BATTERED",
            "conf":1
         },
         {
            "name":"ENTERING",
            "conf":1
         },
         {
            "name":"OVERDONE",
            "conf":1
         },
         {
            "name":"STACCATO",
            "conf":1
         },
         {
            "name":"STINGRAY",
            "conf":1
         },
         {
            "name":"ROADRAGE",
            "conf":1
         },
         {
            "name":"MEDDLING",
            "conf":1
         }
      ]
   },
   {
      "clue":"Island east of Java",
      "length":4,
      "position":10,
      "answer":"    ",
      "startx":12,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"BALI",
            "conf":5
         },
         {
            "name":"MAUI",
            "conf":3
         },
         {
            "name":"ELBA",
            "conf":3
         },
         {
            "name":"JAVA",
            "conf":3
         },
         {
            "name":"GUAM",
            "conf":3
         },
         {
            "name":"UPAS",
            "conf":2
         },
         {
            "name":"ICEE",
            "conf":2
         },
         {
            "name":"EDEN",
            "conf":2
         },
         {
            "name":"ARON",
            "conf":2
         },
         {
            "name":"ELIA",
            "conf":2
         },
         {
            "name":"ABRA",
            "conf":2
         }
      ]
   },
   {
      "clue":"Z _ zebra",
      "length":4,
      "position":11,
      "answer":"    ",
      "startx":13,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"ASIN",
            "conf":5
         },
         {
            "name":"NAME",
            "conf":2
         },
         {
            "name":"LION",
            "conf":1
         },
         {
            "name":"SOLO",
            "conf":1
         },
         {
            "name":"MANE",
            "conf":1
         },
         {
            "name":"HOOF",
            "conf":1
         },
         {
            "name":"FOAL",
            "conf":1
         },
         {
            "name":"MARE",
            "conf":1
         },
         {
            "name":"HERD",
            "conf":1
         },
         {
            "name":"PREY",
            "conf":1
         },
         {
            "name":"IZZO",
            "conf":1
         },
         {
            "name":"YVES",
            "conf":1
         },
         {
            "name":"LIZA",
            "conf":1
         },
         {
            "name":"TOME",
            "conf":1
         },
         {
            "name":"TYPO",
            "conf":1
         },
         {
            "name":"IROC",
            "conf":1
         },
         {
            "name":"TOLL",
            "conf":1
         },
         {
            "name":"NERD",
            "conf":1
         },
         {
            "name":"MOAS",
            "conf":1
         },
         {
            "name":"ZETA",
            "conf":1
         },
         {
            "name":"OTEA",
            "conf":1
         }
      ]
   },
   {
      "clue":"Like lowest—mileage driving",
      "length":4,
      "position":12,
      "answer":"    ",
      "startx":14,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"CITY",
            "conf":4
         },
         {
            "name":"USES",
            "conf":1
         },
         {
            "name":"USED",
            "conf":1
         },
         {
            "name":"WEAR",
            "conf":1
         },
         {
            "name":"AREA",
            "conf":1
         },
         {
            "name":"HAIR",
            "conf":1
         },
         {
            "name":"LAST",
            "conf":1
         },
         {
            "name":"ATOM",
            "conf":1
         },
         {
            "name":"IOTA",
            "conf":1
         },
         {
            "name":"SCUM",
            "conf":1
         },
         {
            "name":"SKAT",
            "conf":1
         },
         {
            "name":"ASIA",
            "conf":1
         },
         {
            "name":"EYRE",
            "conf":1
         },
         {
            "name":"TOUS",
            "conf":1
         },
         {
            "name":"UHRY",
            "conf":1
         },
         {
            "name":"HOKE",
            "conf":1
         },
         {
            "name":"MISS",
            "conf":1
         },
         {
            "name":"DEMO",
            "conf":1
         },
         {
            "name":"GONE",
            "conf":1
         }
      ]
   },
   {
      "clue":"Diamonds, slangily",
      "length":3,
      "position":13,
      "answer":"   ",
      "startx":15,
      "starty":1,
      "orientation":"down",
      "answers":[
         {
            "name":"ICE",
            "conf":5
         },
         {
            "name":"ARE",
            "conf":1
         },
         {
            "name":"HER",
            "conf":1
         },
         {
            "name":"LSD",
            "conf":1
         },
         {
            "name":"SKY",
            "conf":1
         },
         {
            "name":"UMP",
            "conf":1
         },
         {
            "name":"BAT",
            "conf":1
         },
         {
            "name":"RED",
            "conf":1
         },
         {
            "name":"IMA",
            "conf":1
         },
         {
            "name":"IAM",
            "conf":1
         }
      ]
   },
   {
      "clue":"Stitch up",
      "length":3,
      "position":21,
      "answer":"   ",
      "startx":5,
      "starty":4,
      "orientation":"down",
      "answers":[
         {
            "name":"SEW",
            "conf":5
         },
         {
            "name":"HEM",
            "conf":1
         },
         {
            "name":"SAW",
            "conf":1
         },
         {
            "name":"ERR",
            "conf":1
         },
         {
            "name":"ZAG",
            "conf":1
         }
      ]
   },
   {
      "clue":"Bars at the checkout counter: Abbr.",
      "length":3,
      "position":22,
      "answer":"   ",
      "startx":10,
      "starty":4,
      "orientation":"down",
      "answers":[
         {
            "name":"UPC",
            "conf":5
         },
         {
            "name":"CFO",
            "conf":2
         },
         {
            "name":"ATM",
            "conf":2
         },
         {
            "name":"RAG",
            "conf":2
         },
         {
            "name":"NOR",
            "conf":1
         },
         {
            "name":"FUN",
            "conf":1
         },
         {
            "name":"CSA",
            "conf":1
         },
         {
            "name":"ICE",
            "conf":1
         }
      ]
   },
   {
      "clue":"Eats like a bird",
      "length":5,
      "position":25,
      "answer":"     ",
      "startx":1,
      "starty":6,
      "orientation":"down",
      "answers":[
         {
            "name":"PECKS",
            "conf":5
         },
         {
            "name":"RENDS",
            "conf":3
         },
         {
            "name":"GNAWS",
            "conf":3
         },
         {
            "name":"AVIAN",
            "conf":3
         },
         {
            "name":"TRILL",
            "conf":3
         },
         {
            "name":"TWEET",
            "conf":3
         },
         {
            "name":"CHIRR",
            "conf":3
         },
         {
            "name":"AIRTO",
            "conf":2
         },
         {
            "name":"WADER",
            "conf":2
         },
         {
            "name":"PERCH",
            "conf":2
         },
         {
            "name":"MILNE",
            "conf":2
         },
         {
            "name":"SERIN",
            "conf":2
         },
         {
            "name":"CAWED",
            "conf":2
         },
         {
            "name":"TAKES",
            "conf":1
         },
         {
            "name":"JAMES",
            "conf":1
         },
         {
            "name":"BOLTS",
            "conf":1
         },
         {
            "name":"BURNS",
            "conf":1
         },
         {
            "name":"FLESH",
            "conf":1
         },
         {
            "name":"MELTS",
            "conf":1
         },
         {
            "name":"WEARS",
            "conf":1
         },
         {
            "name":"COMMA",
            "conf":1
         },
         {
            "name":"ALTON",
            "conf":1
         },
         {
            "name":"OTTER",
            "conf":1
         }
      ]
   },
   {
      "clue":"Maui greeting",
      "length":5,
      "position":26,
      "answer":"     ",
      "startx":2,
      "starty":6,
      "orientation":"down",
      "answers":[
         {
            "name":"ALOHA",
            "conf":5
         },
         {
            "name":"NENES",
            "conf":1
         },
         {
            "name":"HULAS",
            "conf":1
         },
         {
            "name":"LANAI",
            "conf":1
         },
         {
            "name":"HAOLE",
            "conf":1
         },
         {
            "name":"WOWIE",
            "conf":1
         },
         {
            "name":"ISLES",
            "conf":1
         },
         {
            "name":"KIHEI",
            "conf":1
         },
         {
            "name":"LUAUS",
            "conf":1
         }
      ]
   },
   {
      "clue":"Louise and Turner",
      "length":5,
      "position":27,
      "answer":"     ",
      "startx":3,
      "starty":6,
      "orientation":"down",
      "answers":[
         {
            "name":"TINAS",
            "conf":5
         },
         {
            "name":"LANAS",
            "conf":2
         },
         {
            "name":"BOGAN",
            "conf":1
         },
         {
            "name":"OPERA",
            "conf":1
         },
         {
            "name":"GEENA",
            "conf":1
         },
         {
            "name":"ANITA",
            "conf":1
         },
         {
            "name":"EMAIL",
            "conf":1
         },
         {
            "name":"BANFF",
            "conf":1
         }
      ]
   },
   {
      "clue":"Carry on",
      "length":4,
      "position":29,
      "answer":"    ",
      "startx":7,
      "starty":6,
      "orientation":"down",
      "answers":[
         {
            "name":"RAGE",
            "conf":5
         },
         {
            "name":"WORK",
            "conf":5
         },
         {
            "name":"LAST",
            "conf":5
         },
         {
            "name":"KEEP",
            "conf":5
         },
         {
            "name":"LIVE",
            "conf":5
         },
         {
            "name":"PLAY",
            "conf":5
         },
         {
            "name":"YELL",
            "conf":5
         },
         {
            "name":"CARE",
            "conf":5
         },
         {
            "name":"GOON",
            "conf":5
         },
         {
            "name":"WAGE",
            "conf":5
         },
         {
            "name":"RAVE",
            "conf":5
         },
         {
            "name":"WAIL",
            "conf":5
         },
         {
            "name":"MAKE",
            "conf":5
         },
         {
            "name":"TALK",
            "conf":5
         },
         {
            "name":"HOLD",
            "conf":5
         },
         {
            "name":"FUSS",
            "conf":5
         },
         {
            "name":"TEND",
            "conf":5
         },
         {
            "name":"RANT",
            "conf":5
         },
         {
            "name":"COPE",
            "conf":5
         }
      ]
   },
   {
      "clue":"Keyboard key",
      "length":5,
      "position":30,
      "answer":"     ",
      "startx":8,
      "starty":6,
      "orientation":"down",
      "answers":[
         {
            "name":"ENTER",
            "conf":5
         },
         {
            "name":"SHIFT",
            "conf":5
         },
         {
            "name":"SPACE",
            "conf":2
         },
         {
            "name":"SCALE",
            "conf":1
         },
         {
            "name":"ETUDE",
            "conf":1
         },
         {
            "name":"PIANO",
            "conf":1
         },
         {
            "name":"ORGAN",
            "conf":1
         },
         {
            "name":"TATUM",
            "conf":1
         },
         {
            "name":"BASIE",
            "conf":1
         },
         {
            "name":"TYPES",
            "conf":1
         },
         {
            "name":"SATIE",
            "conf":1
         },
         {
            "name":"ERROL",
            "conf":1
         },
         {
            "name":"SYNTH",
            "conf":1
         },
         {
            "name":"COMMA",
            "conf":1
         },
         {
            "name":"CASIO",
            "conf":1
         },
         {
            "name":"BACKS",
            "conf":1
         },
         {
            "name":"MOOGS",
            "conf":1
         },
         {
            "name":"PIANI",
            "conf":1
         },
         {
            "name":"EMAIL",
            "conf":1
         },
         {
            "name":"ARROW",
            "conf":1
         }
      ]
   },
   {
      "clue":"Comedian‘s stock",
      "length":4,
      "position":32,
      "answer":"    ",
      "startx":12,
      "starty":6,
      "orientation":"down",
      "answers":[
         {
            "name":"HAHA",
            "conf":1
         },
         {
            "name":"LENO",
            "conf":1
         },
         {
            "name":"ARTE",
            "conf":1
         },
         {
            "name":"SAHL",
            "conf":1
         },
         {
            "name":"RYES",
            "conf":1
         },
         {
            "name":"GINS",
            "conf":1
         },
         {
            "name":"DJIA",
            "conf":1
         },
         {
            "name":"AMMO",
            "conf":1
         },
         {
            "name":"OILS",
            "conf":1
         },
         {
            "name":"EGGS",
            "conf":1
         },
         {
            "name":"TALC",
            "conf":1
         },
         {
            "name":"RUSH",
            "conf":1
         },
         {
            "name":"STAT",
            "conf":1
         },
         {
            "name":"ABEE",
            "conf":1
         },
         {
            "name":"EATA",
            "conf":1
         },
         {
            "name":"MELS",
            "conf":1
         },
         {
            "name":"EURE",
            "conf":1
         },
         {
            "name":"MARG",
            "conf":1
         }
      ]
   },
   {
      "clue":"Sonora \"so |ong\"",
      "length":5,
      "position":33,
      "answer":"     ",
      "startx":13,
      "starty":6,
      "orientation":"down",
      "answers":[
         {
            "name":"ADIOS",
            "conf":2
         },
         {
            "name":"YAQUI",
            "conf":1
         },
         {
            "name":"SENOR",
            "conf":1
         },
         {
            "name":"SALUD",
            "conf":1
         },
         {
            "name":"TACOS",
            "conf":1
         },
         {
            "name":"SALSA",
            "conf":1
         },
         {
            "name":"CHILI",
            "conf":1
         },
         {
            "name":"AMIGO",
            "conf":1
         }
      ]
   },
   {
      "clue":"Washer cycle",
      "length":5,
      "position":34,
      "answer":"     ",
      "startx":14,
      "starty":6,
      "orientation":"down",
      "answers":[
         {
            "name":"RINSE",
            "conf":5
         },
         {
            "name":"HOSER",
            "conf":1
         },
         {
            "name":"STORM",
            "conf":1
         },
         {
            "name":"LEAKY",
            "conf":1
         },
         {
            "name":"SUDSY",
            "conf":1
         },
         {
            "name":"DRYER",
            "conf":1
         },
         {
            "name":"DRIPS",
            "conf":1
         },
         {
            "name":"RESET",
            "conf":1
         },
         {
            "name":"CYCLE",
            "conf":1
         },
         {
            "name":"VANES",
            "conf":1
         },
         {
            "name":"LOADS",
            "conf":1
         },
         {
            "name":"AMANA",
            "conf":1
         },
         {
            "name":"STAGE",
            "conf":1
         },
         {
            "name":"HABIT",
            "conf":1
         },
         {
            "name":"ORBIT",
            "conf":1
         },
         {
            "name":"DRIVE",
            "conf":1
         },
         {
            "name":"PEDAL",
            "conf":1
         },
         {
            "name":"ROUND",
            "conf":1
         },
         {
            "name":"PHASE",
            "conf":1
         },
         {
            "name":"CHAIN",
            "conf":1
         },
         {
            "name":"WHEEL",
            "conf":1
         },
         {
            "name":"RINSP",
            "conf":1
         },
         {
            "name":"MONTH",
            "conf":1
         },
         {
            "name":"KNEAD",
            "conf":1
         },
         {
            "name":"ROREM",
            "conf":1
         },
         {
            "name":"REAIR",
            "conf":1
         },
         {
            "name":"HONDA",
            "conf":1
         },
         {
            "name":"BIKER",
            "conf":1
         },
         {
            "name":"KNITS",
            "conf":1
         },
         {
            "name":"SLEEP",
            "conf":1
         }
      ]
   },
   {
      "clue":"\"Contact\" author Carl",
      "length":5,
      "position":35,
      "answer":"     ",
      "startx":15,
      "starty":6,
      "orientation":"down",
      "answers":[
         {
            "name":"SAGAN",
            "conf":5
         },
         {
            "name":"SUEDE",
            "conf":1
         },
         {
            "name":"WEBER",
            "conf":1
         },
         {
            "name":"CRAIG",
            "conf":1
         },
         {
            "name":"ENTER",
            "conf":1
         },
         {
            "name":"ICAHN",
            "conf":1
         },
         {
            "name":"SWEEP",
            "conf":1
         },
         {
            "name":"TASTE",
            "conf":1
         },
         {
            "name":"SHOCK",
            "conf":1
         },
         {
            "name":"CRASH",
            "conf":1
         },
         {
            "name":"PHONE",
            "conf":1
         },
         {
            "name":"MARCH",
            "conf":1
         },
         {
            "name":"ALFRE",
            "conf":1
         },
         {
            "name":"JODIE",
            "conf":1
         },
         {
            "name":"TOUCH",
            "conf":1
         }
      ]
   },
   {
      "clue":"Invites",
      "length":4,
      "position":37,
      "answer":"    ",
      "startx":4,
      "starty":7,
      "orientation":"down",
      "answers":[
         {
            "name":"BEGS",
            "conf":5
         },
         {
            "name":"BIDS",
            "conf":5
         },
         {
            "name":"ASKS",
            "conf":5
         },
         {
            "name":"WOOS",
            "conf":5
         },
         {
            "name":"BYOB",
            "conf":1
         },
         {
            "name":"NCAA",
            "conf":1
         }
      ]
   },
   {
      "clue":"Pate||a‘s place",
      "length":4,
      "position":39,
      "answer":"    ",
      "startx":9,
      "starty":7,
      "orientation":"down",
      "answers":[
         {
            "name":"UNIV",
            "conf":2
         },
         {
            "name":"DESK",
            "conf":2
         },
         {
            "name":"DOME",
            "conf":1
         },
         {
            "name":"HEAD",
            "conf":1
         },
         {
            "name":"TETE",
            "conf":1
         },
         {
            "name":"FOIE",
            "conf":1
         },
         {
            "name":"GRAS",
            "conf":1
         },
         {
            "name":"HATS",
            "conf":1
         }
      ]
   },
   {
      "clue":"Get snockered",
      "length":8,
      "position":42,
      "answer":"        ",
      "startx":5,
      "starty":8,
      "orientation":"down",
      "answers":[
         {
            "name":"TIEONEON",
            "conf":5
         },
         {
            "name":"STEPONIT",
            "conf":1
         },
         {
            "name":"SNAPTOIT",
            "conf":1
         },
         {
            "name":"IGNOREIT",
            "conf":1
         },
         {
            "name":"KEEPCOOL",
            "conf":1
         },
         {
            "name":"TRAVOLTA",
            "conf":1
         },
         {
            "name":"CHEESEIT",
            "conf":1
         },
         {
            "name":"SHOOSHOO",
            "conf":1
         },
         {
            "name":"STANDPAT",
            "conf":1
         },
         {
            "name":"BEEPBEEP",
            "conf":1
         },
         {
            "name":"EDGEWISE",
            "conf":1
         },
         {
            "name":"GOFIGURE",
            "conf":1
         },
         {
            "name":"TIMETOGO",
            "conf":1
         }
      ]
   },
   {
      "clue":"It puts the squeeze on",
      "length":8,
      "position":43,
      "answer":"        ",
      "startx":10,
      "starty":8,
      "orientation":"down",
      "answers":[
         {
            "name":"ANACONDA",
            "conf":5
         },
         {
            "name":"HEIMLICH",
            "conf":3
         },
         {
            "name":"SPEEDSUP",
            "conf":2
         },
         {
            "name":"INTIMATE",
            "conf":1
         },
         {
            "name":"MISTRESS",
            "conf":1
         },
         {
            "name":"LADYLOVE",
            "conf":1
         },
         {
            "name":"OLDFLAME",
            "conf":1
         }
      ]
   },
   {
      "clue":"Hindu title",
      "length":3,
      "position":48,
      "answer":"   ",
      "startx":6,
      "starty":10,
      "orientation":"down",
      "answers":[
         {
            "name":"SRI",
            "conf":5
         },
         {
            "name":"REM",
            "conf":1
         },
         {
            "name":"XXX",
            "conf":1
         },
         {
            "name":"TAL",
            "conf":1
         },
         {
            "name":"BAB",
            "conf":1
         },
         {
            "name":"OMS",
            "conf":1
         },
         {
            "name":"RAJ",
            "conf":1
         },
         {
            "name":"REH",
            "conf":1
         },
         {
            "name":"APU",
            "conf":1
         },
         {
            "name":"EON",
            "conf":1
         }
      ]
   },
   {
      "clue":"Singer McLean",
      "length":3,
      "position":50,
      "answer":"   ",
      "startx":11,
      "starty":10,
      "orientation":"down",
      "answers":[
         {
            "name":"DON",
            "conf":5
         },
         {
            "name":"LIN",
            "conf":1
         },
         {
            "name":"PIE",
            "conf":1
         },
         {
            "name":"CIA",
            "conf":1
         }
      ]
   },
   {
      "clue":"Made a choice",
      "length":5,
      "position":53,
      "answer":"     ",
      "startx":7,
      "starty":11,
      "orientation":"down",
      "answers":[
         {
            "name":"OPTED",
            "conf":5
         },
         {
            "name":"HASTO",
            "conf":2
         },
         {
            "name":"ELECT",
            "conf":2
         },
         {
            "name":"OPTER",
            "conf":2
         },
         {
            "name":"HADTO",
            "conf":2
         },
         {
            "name":"FATED",
            "conf":2
         },
         {
            "name":"NOWIN",
            "conf":2
         },
         {
            "name":"MYBAD",
            "conf":2
         },
         {
            "name":"NIXON",
            "conf":2
         },
         {
            "name":"RODIN",
            "conf":2
         },
         {
            "name":"FAUST",
            "conf":2
         },
         {
            "name":"MONET",
            "conf":2
         },
         {
            "name":"GOMER",
            "conf":2
         },
         {
            "name":"AIMED",
            "conf":2
         },
         {
            "name":"VWBUG",
            "conf":2
         },
         {
            "name":"SHARI",
            "conf":2
         },
         {
            "name":"LOWED",
            "conf":2
         },
         {
            "name":"VOTED",
            "conf":2
         },
         {
            "name":"ERRED",
            "conf":2
         },
         {
            "name":"CAWED",
            "conf":2
         }
      ]
   },
   {
      "clue":"Put forward",
      "length":5,
      "position":55,
      "answer":"     ",
      "startx":12,
      "starty":11,
      "orientation":"down",
      "answers":[
         {
            "name":"STATE",
            "conf":5
         },
         {
            "name":"PLEAD",
            "conf":5
         },
         {
            "name":"OFFER",
            "conf":5
         },
         {
            "name":"TABLE",
            "conf":5
         },
         {
            "name":"RAISE",
            "conf":5
         },
         {
            "name":"FAVOR",
            "conf":5
         },
         {
            "name":"POSED",
            "conf":5
         },
         {
            "name":"POSIT",
            "conf":5
         },
         {
            "name":"ALONG",
            "conf":1
         },
         {
            "name":"FRONT",
            "conf":1
         },
         {
            "name":"FIRST",
            "conf":1
         },
         {
            "name":"SASSY",
            "conf":1
         },
         {
            "name":"HURRY",
            "conf":1
         },
         {
            "name":"AHEAD",
            "conf":1
         },
         {
            "name":"NURSE",
            "conf":1
         },
         {
            "name":"SERVE",
            "conf":1
         },
         {
            "name":"ROUTE",
            "conf":1
         },
         {
            "name":"BEGIN",
            "conf":1
         },
         {
            "name":"FORGE",
            "conf":1
         },
         {
            "name":"FLASH",
            "conf":1
         },
         {
            "name":"SHOVE",
            "conf":1
         },
         {
            "name":"IMPEL",
            "conf":1
         },
         {
            "name":"LEDER",
            "conf":1
         },
         {
            "name":"JACOB",
            "conf":1
         },
         {
            "name":"RESET",
            "conf":1
         },
         {
            "name":"KAYAK",
            "conf":1
         },
         {
            "name":"RELAY",
            "conf":1
         },
         {
            "name":"FORTH",
            "conf":1
         },
         {
            "name":"MARCH",
            "conf":1
         },
         {
            "name":"URGED",
            "conf":1
         },
         {
            "name":"AVANT",
            "conf":1
         },
         {
            "name":"TIMID",
            "conf":1
         }
      ]
   },
   {
      "clue":"Mrs. Dithers",
      "length":4,
      "position":56,
      "answer":"    ",
      "startx":2,
      "starty":12,
      "orientation":"down",
      "answers":[
         {
            "name":"CORA",
            "conf":5
         },
         {
            "name":"AGER",
            "conf":1
         },
         {
            "name":"BOSS",
            "conf":1
         }
      ]
   },
   {
      "clue":"Dump problem",
      "length":4,
      "position":57,
      "answer":"    ",
      "startx":3,
      "starty":12,
      "orientation":"down",
      "answers":[
         {
            "name":"ODOR",
            "conf":5
         },
         {
            "name":"CAST",
            "conf":1
         },
         {
            "name":"MESS",
            "conf":1
         },
         {
            "name":"KILL",
            "conf":1
         },
         {
            "name":"SELL",
            "conf":1
         },
         {
            "name":"SLUR",
            "conf":1
         },
         {
            "name":"DROP",
            "conf":1
         },
         {
            "name":"HOME",
            "conf":1
         },
         {
            "name":"SPOT",
            "conf":1
         },
         {
            "name":"HOLE",
            "conf":1
         },
         {
            "name":"TAKE",
            "conf":1
         },
         {
            "name":"HEAP",
            "conf":1
         },
         {
            "name":"FALL",
            "conf":1
         },
         {
            "name":"GIBE",
            "conf":1
         },
         {
            "name":"VOID",
            "conf":1
         },
         {
            "name":"BOLT",
            "conf":1
         },
         {
            "name":"JILT",
            "conf":1
         },
         {
            "name":"JUNK",
            "conf":1
         },
         {
            "name":"MOCK",
            "conf":1
         },
         {
            "name":"SLUM",
            "conf":1
         },
         {
            "name":"FILL",
            "conf":1
         },
         {
            "name":"DUDE",
            "conf":1
         },
         {
            "name":"KEEP",
            "conf":1
         },
         {
            "name":"STER",
            "conf":1
         },
         {
            "name":"AMMO",
            "conf":1
         },
         {
            "name":"BURY",
            "conf":1
         }
      ]
   },
   {
      "clue":"El f (weather factor)",
      "length":4,
      "position":58,
      "answer":"    ",
      "startx":4,
      "starty":12,
      "orientation":"down",
      "answers":[
         {
            "name":"NINO",
            "conf":2
         },
         {
            "name":"DARE",
            "conf":1
         },
         {
            "name":"UGHS",
            "conf":1
         },
         {
            "name":"EELS",
            "conf":1
         },
         {
            "name":"SULU",
            "conf":1
         },
         {
            "name":"FEAR",
            "conf":1
         },
         {
            "name":"RPMS",
            "conf":1
         },
         {
            "name":"LISP",
            "conf":1
         }
      ]
   },
   {
      "clue":"Like some pizza orders",
      "length":4,
      "position":59,
      "answer":"    ",
      "startx":8,
      "starty":12,
      "orientation":"down",
      "answers":[
         {
            "name":"TOGO",
            "conf":5
         },
         {
            "name":"THIN",
            "conf":3
         },
         {
            "name":"PIES",
            "conf":2
         },
         {
            "name":"NOID",
            "conf":1
         },
         {
            "name":"LILI",
            "conf":1
         },
         {
            "name":"GISH",
            "conf":1
         },
         {
            "name":"OREO",
            "conf":1
         },
         {
            "name":"DISH",
            "conf":1
         },
         {
            "name":"LIRA",
            "conf":1
         },
         {
            "name":"CAIN",
            "conf":1
         }
      ]
   },
   {
      "clue":"Gulf land",
      "length":4,
      "position":60,
      "answer":"    ",
      "startx":9,
      "starty":12,
      "orientation":"down",
      "answers":[
         {
            "name":"IRAN",
            "conf":5
         },
         {
            "name":"OMAN",
            "conf":5
         },
         {
            "name":"IRAQ",
            "conf":2
         },
         {
            "name":"ADEN",
            "conf":1
         },
         {
            "name":"TIDE",
            "conf":1
         },
         {
            "name":"ORAN",
            "conf":1
         },
         {
            "name":"ARTA",
            "conf":1
         },
         {
            "name":"EDOM",
            "conf":1
         },
         {
            "name":"SIAM",
            "conf":1
         },
         {
            "name":"EAST",
            "conf":1
         },
         {
            "name":"INTO",
            "conf":1
         },
         {
            "name":"NEER",
            "conf":1
         },
         {
            "name":"THRO",
            "conf":1
         },
         {
            "name":"BALI",
            "conf":1
         },
         {
            "name":"BEEN",
            "conf":1
         },
         {
            "name":"NMEX",
            "conf":1
         },
         {
            "name":"LAOS",
            "conf":1
         },
         {
            "name":"LALA",
            "conf":1
         },
         {
            "name":"STAN",
            "conf":1
         },
         {
            "name":"IFBY",
            "conf":1
         },
         {
            "name":"EBAN",
            "conf":1
         }
      ]
   },
   {
      "clue":"Rick's love in \"Casablanca\"",
      "length":4,
      "position":61,
      "answer":"    ",
      "startx":13,
      "starty":12,
      "orientation":"down",
      "answers":[
         {
            "name":"ILSA",
            "conf":5
         },
         {
            "name":"LUND",
            "conf":4
         },
         {
            "name":"ILSE",
            "conf":2
         },
         {
            "name":"LORR",
            "conf":2
         },
         {
            "name":"AMAS",
            "conf":2
         },
         {
            "name":"PUTA",
            "conf":2
         },
         {
            "name":"ERIC",
            "conf":2
         },
         {
            "name":"ABRA",
            "conf":2
         },
         {
            "name":"EROS",
            "conf":2
         },
         {
            "name":"ROSE",
            "conf":2
         },
         {
            "name":"ROLF",
            "conf":2
         }
      ]
   },
   {
      "clue":"Something shed",
      "length":4,
      "position":62,
      "answer":"    ",
      "startx":14,
      "starty":12,
      "orientation":"down",
      "answers":[
         {
            "name":"TEAR",
            "conf":5
         },
         {
            "name":"CAST",
            "conf":1
         },
         {
            "name":"CAMP",
            "conf":1
         },
         {
            "name":"GIVE",
            "conf":1
         },
         {
            "name":"DROP",
            "conf":1
         },
         {
            "name":"LOSE",
            "conf":1
         },
         {
            "name":"SKIN",
            "conf":1
         },
         {
            "name":"BARE",
            "conf":1
         },
         {
            "name":"BEAM",
            "conf":1
         },
         {
            "name":"FALL",
            "conf":1
         },
         {
            "name":"FLOW",
            "conf":1
         },
         {
            "name":"SLIP",
            "conf":1
         },
         {
            "name":"COTE",
            "conf":1
         },
         {
            "name":"JUNK",
            "conf":1
         },
         {
            "name":"EMIT",
            "conf":1
         },
         {
            "name":"POUR",
            "conf":1
         },
         {
            "name":"MOLT",
            "conf":1
         },
         {
            "name":"DOFF",
            "conf":1
         },
         {
            "name":"THEE",
            "conf":1
         },
         {
            "name":"CRIB",
            "conf":1
         },
         {
            "name":"CHAI",
            "conf":1
         },
         {
            "name":"TOOL",
            "conf":1
         },
         {
            "name":"SILO",
            "conf":1
         },
         {
            "name":"GROW",
            "conf":1
         },
         {
            "name":"WEEP",
            "conf":1
         },
         {
            "name":"PEEL",
            "conf":1
         }
      ]
   },
   {
      "clue":"Applicant's goal",
      "length":3,
      "position":63,
      "answer":"   ",
      "startx":1,
      "starty":13,
      "orientation":"down",
      "answers":[
         {
            "name":"JOB",
            "conf":5
         },
         {
            "name":"SRS",
            "conf":1
         },
         {
            "name":"PHD",
            "conf":1
         },
         {
            "name":"ORO",
            "conf":1
         },
         {
            "name":"MET",
            "conf":1
         },
         {
            "name":"HIT",
            "conf":1
         },
         {
            "name":"TAN",
            "conf":1
         },
         {
            "name":"TOP",
            "conf":1
         },
         {
            "name":"SET",
            "conf":1
         }
      ]
   },
   {
      "clue":"Expected in",
      "length":3,
      "position":66,
      "answer":"   ",
      "startx":15,
      "starty":13,
      "orientation":"down",
      "answers":[
         {
            "name":"DUE",
            "conf":5
         },
         {
            "name":"ETA",
            "conf":2
         },
         {
            "name":"SAW",
            "conf":1
         },
         {
            "name":"TSK",
            "conf":1
         },
         {
            "name":"ODD",
            "conf":1
         },
         {
            "name":"ETD",
            "conf":1
         },
         {
            "name":"PAR",
            "conf":1
         },
         {
            "name":"YES",
            "conf":1
         }
      ]
   }
]

module.exports.array = array;
